# Generated by Django 5.2.5 on 2025-08-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ai_logs',
            table='ai_logs',
        ),
        migrations.AlterModelTable(
            name='recommendation',
            table='recommendations',
        ),
    ]
