# Generated by Django 5.2.5 on 2025-08-11 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Context',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('INSTAGRAM', 'Instagram'), ('NOTES', 'Notes'), ('OTHER', 'Other')], max_length=60)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='context_image/')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link'), ('other', 'Other')], max_length=100)),
                ('time', models.DateTimeField()),
                ('is_task_related', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_task_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_context', to='tasks.tasks')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_context', to='users.user')),
            ],
        ),
    ]
