# Generated by Django 5.2.5 on 2025-08-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='daily_context',
            table='daily_context',
        ),
    ]
