# Generated by Django 5.2.5 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_daily_context_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_context',
            name='content',
            field=models.TextField(),
        ),
    ]
