# Generated by Django 5.2.5 on 2025-08-11 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_module', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=225)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('priority', models.IntegerField(default=0)),
                ('priority_reason', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING, Pending', 'Pending'), ('IN_PROGRESS,In_Progress', 'In Progress'), ('FINISHED, Finished', 'Finished'), ('CANCELLED, Cancelled', 'Cancelled')], default='PENDING, Pending', max_length=30)),
                ('is_timely_finished', models.BooleanField(default=True)),
                ('ai_generated_deadline', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.categories')),
                ('recommendation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_module.recommendation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('STATUS_CHANGE', 'Status_Change'), ('PRIORITY_UPDATED', 'Priority_Updated'), ('DEADLINE_CHANGED', 'Deadline_Changed')], max_length=50)),
                ('prev_event', models.CharField(max_length=255)),
                ('current_event', models.CharField(max_length=255)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], default='USER', max_length=50)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='tasks.tasks')),
            ],
        ),
    ]
