# Generated by Django 5.2.5 on 2025-08-12 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='task_history',
            table='task_history',
        ),
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
