# Generated by Django 5.2.5 on 2025-08-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_categories_table_alter_task_history_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('PENDING, Pending', 'Pending'), ('IN_PROGRESS,In_Progress', 'In Progress'), ('FINISHED, Finished', 'Finished'), ('CANCELLED, Cancelled', 'Cancelled'), ('OVERDUE OVERDUE', 'Overdue')], default='PENDING, Pending', max_length=30),
        ),
    ]
