# Generated by Django 5.2.5 on 2025-08-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasks_status'),
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.user'),
        ),
    ]
