# Generated by Django 5.2.5 on 2025-08-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_categories_user_id'),
        ('users', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='users.user'),
        ),
    ]
