# Generated by Django 5.2.5 on 2025-08-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_priority_reason_alter_tasks_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_history',
            name='event',
            field=models.CharField(choices=[('STATUS_UPDATED', 'Status_Updated'), ('PRIORITY_UPDATED', 'Priority_Updated'), ('DEADLINE_UPDATED', 'Deadline_Updated'), ('CREATED', 'Created'), ('REMOVED', 'Removed'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
