# Generated by Django 5.2.5 on 2025-08-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_tasks_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
