# Generated by Django 5.2.5 on 2025-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
