# Generated by Django 5.2.5 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tasks_finished_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='created_by',
            field=models.CharField(default='User', max_length=60),
        ),
    ]
