# Generated by Django 5.2.5 on 2025-08-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_tasks_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='category_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.categories'),
        ),
    ]
